### ISSUE TITLE
A question about the benchmark

### ISSUE THREAD

**Issue by Celthi** [dtolnay/dircnt#3]
When it says "faster" than "ls -f | wc -l", do we have some benchmark data to justify it?

**Comment by dtolnay** [comment]
In the use case that I wrote it for, this program took 37% less time to count the same large directory i.e. counted 59% more entries per unit time.

**Comment by TheAwiteb** [comment]
![image](https://user-images.githubusercontent.com/59842932/197053363-85a13006-8b89-429c-8236-16e2618711ea.png)

**Comment by TheAwiteb** [comment]
Sorry the `ls` above is alias for exa, the time with [`ls`](https://en.wikipedia.org/wiki/Ls) is

```
Executed in    1.62 secs    fish           external
   usr time    1.41 secs  245.00 micros    1.41 secs
   sys time    0.22 secs  375.00 micros    0.22 secs
```

**Comment by dtolnay** [comment]
`ls -f` is a more useful comparison. `ls` spends most of its time buffering and sorting the entries.

**Comment by TheAwiteb** [comment]
> `ls -f` is a more useful comparison. `ls` spends most of its time buffering and sorting the entries.

I have close the browser 👀 

```
⟩ time dircnt
1000003

________________________________________________________
Executed in  175.32 millis    fish           external
   usr time   39.87 millis  106.00 micros   39.76 millis
   sys time  135.31 millis  133.00 micros  135.18 millis
```


```
⟩ time ls -f | wc -l
1000005

________________________________________________________
Executed in  225.54 millis    fish           external
   usr time   81.62 millis  313.00 micros   81.31 millis
   sys time  152.93 millis  398.00 micros  152.53 millis
```
